"""
Settings for witches rule the world
"""
import os
BLOG_URL = 'witchesruletheworld.tumblr.com'

TUMBLR = [
    os.environ['WITCHES_CONSUMER_KEY'],
    os.environ['WITCHES_CONSUMER_SECRET'],
    os.environ['WITCHES_OAUTH_TOKEN'],
    os.environ['WITCHES_OAUTH_SECRET']
]

TAGS = [
    'witch',
    'moody',
    'noir',
    'nu goth',
    'gothgoth'
]

BLACKLIST = set([
    "31witches",
    "ass",
    "blood",
    "bloodplay",
    "bloody",
    "boy",
    "boyswillbegirls",
    "breasts",
    "cocksucking",
    "comic",
    "crossdresser",
    "crossdressing",
    "cuts",
    "cutting",
    "daddy",
    "dick",
    "dickgirl",
    "do not reblog",
    "do not reblog pls",
    "do not reblog plz",
    "don't reblog",
    "don't reblog pls",
    "don't reblog plz",
    "dont reblog",
    "dont reblog pls",
    "dont reblog plz",
    "fanart",
    "femboi",
    "fembot",
    "ftm",
    "ftmtransgender",
    "ftm hrt",
    "ftm transgender",
    "ftm transman",
    "futa",
    "futanari",
    "gay boy",
    "gay boys",
    "gay man",
    "gay men",
    "gender hc",
    "genderbend",
    "genderbender",
    "genderswap",
    "he/him",
    "headcanon",
    "herm",
    "hermaphrodite",
    "hot transgender",
    "inktober",
    "inktober2017",
    "ladyboy",
    "ladyboys",
    "lewd",
    "masturbate",
    "masturbating",
    "menlikeus",
    "mindless",
    "naked",
    "no reblog",
    "no reblog plz",
    "no reblog plz",
    "no reblogs",
    "no reblogs plz",
    "no reblogs plz",
    "nsfw",
    "nude",
    "nudity",
    "pre op ftm",
    "play thing",
    "porn",
    "self harm",
    "self-harm",
    "sex",
    "sexual",
    "shamala",
    "shamale",
    "shamela",
    "shamele",
    "shemala",
    "shemale",
    "shemela",
    "shemele",
    "shim",
    "shirtless",
    "siss",
    "sissifaction",
    "sissy",
    "t girl",
    "t-girl",
    "tgirl",
    "topless",
    "toptrans",
    "tranny",
    "trannywomen",
    "trans boy",
    "trans boys",
    "trans guy",
    "trans hc",
    "trans headcanon",
    "trans masc",
    "trans masculine",
    "trans positivity",
    "transboy",
    "transboys",
    "transexuals",
    "transguy",
    "transmasc",
    "transmasculine",
    "transsexual",
    "transvesti",
    "transvestite",
    "trap",
    "traps",
    "truscum",
    "webcomic",
    "witchtober",
    "xdresser"
])

SAFE_EMOJIS = [
    ':innocent:',
    ':grinning:',
    ':smiley:',
    ':wink:',
    ':blush:',
    ':relaxed:',
    ':yum:',
    ':innocent:',
    ':heart_eyes:',
    ':kissing_heart:',
    ':heartpulse:',
    ':astonished:',
    ':smile_cat:',
    ':heart_eyes_cat:',
    ':ok_woman:',
    ':bow:',
    ':raised_hands:',
    ':eyes:',
    ':thumbsup:',
    ':ok_hand:',
    ':tulip:',
    ':rose:',
    ':bouquet:',
    ':herb:',
    ':leaves:',
    ':rabbit:',
    ':hatching_chick:',
    ':hatched_chick:',
    ':dog:',
    ':gift_heart:',
    ':monkey_face:',
    ':see_no_evil:',
    ':hear_no_evil:',
    ':whale:',
    ':frog:',
    ':octopus:',
    ':sunny:',
    ':star2:',
    ':star:',
    ':stars:',
    ':sunrise:',
    ':tada:',
    ':confetti_ball:',
    ':sparkles:',
    ':two_hearts:',
    ':cupid:',
    ':+1:',
    ':smiley_cat:'
    ':sparkling_heart:',
    ':heart:',
    ':purple_heart:',
    ':yellow_heart:',
    ':green_heart:',
    ':blue_heart:',
    ':dancer:',
    ':snowboarder:',
    ':bangbang:',
    ':exclamation:',
    ':100:'
]
